GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/609fa158dd6cfa166814df67

###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Coding"
}